services:
  vnc-server:
    build:
      context: https://raw.githubusercontent.com/Linkyrex/3Dstation/refs/heads/main/
      dockerfile: Dockerfile
    ports:
      - "5910:5900"
    environment:
      - USER=topi
      - RESOLUTION=800x480
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
