services:
  vnc-server:
    build:
      context: https://github.com/Linkyrex/3Dstation/blob/b3a6c6680bd89f4ddadfdd873b2eeb96504e6427/Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5910:5900"
    environment:
      - USER=topi
      - RESOLUTION=800x480
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
